
# -- Nombre del fichero a ensamblar
NAME = 'simplez'
DEPS = Split('simplez.v genram.v {0}/dividerp1.v {0}/uart_tx.v {0}/baudgen_tx.v \
              {0}/uart_rx.v {0}/baudgen_rx.v'.format('peripherals'))
PCF = NAME + '.pcf'

# -- Constructor para sintetizar
synth = Builder(action='yosys -p \"synth_ice40 -blif $TARGET\" $SOURCES',
                suffix='.blif',
                src_suffix='.v')

pnr = Builder(action='arachne-pnr -d 1k -o $TARGET -p {} $SOURCE'.format(PCF),
              suffix='.asc',
              src_suffix='.blif')

bitstream = Builder(action='icepack $SOURCE $TARGET',
                    suffix='.bin',
                    src_suffix='.asc')

# -- Construccion del informe de tiempos
time_rpt = Builder(action='icetime -mtr $TARGET $SOURCE',
                   suffix='.rpt',
                   src_suffix='.asc')

# -- Construir el entorno
env = Environment(BUILDERS={'Synth': synth, 'PnR': pnr, 'Bin': bitstream, 'Time': time_rpt})


# -- Sintesis complesta: de verilog a bitstream
blif = env.Synth(NAME, DEPS)
asc = env.PnR([blif, PCF])
Default(env.Bin(asc))

# -- Objetivo time para calcular el tiempo
rpt = env.Time(asc)
t = env.Alias('time', rpt)

# -- These is for cleaning also the .rpt file (that were generated using the time target)
if GetOption('clean'):
    env.Default(t)

# env.Time(NAME)
